### ISSUE TITLE
Crash if device offline

### ISSUE THREAD

**Issue by woessmich** [smarthausleben/ioBroker.wamo#1]
**Describe the bug**  
The adapter crashes after 5 attempts to connect to the device if it is offline.

**To Reproduce**  
Set device offline, start adapter

**Expected behavior**  
Retry after increasingly longer intervals but do not crash

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
Not required

**Versions:**  
 - Adapter version: 0.1.4

**Additional context**

**Comment by smarthausleben** [comment]
fixed in release v0.1.5
