### ISSUE TITLE
Deutsche Wasserhärte

### ISSUE THREAD

**Issue by weindler** [smarthausleben/ioBroker.wamo#16]
Hallo,

seit dem Update auf die 0.2.9 habe ich keinen Fehler mehr zu verzeichnen, läuft jetzt seit 24 Stunden Problemlos.

Nun zum Wasserhärte Thema, wenn man auf den Syrconnect selber geht, dann habe ich das gelbe ICON, heißt Wasserhärte von 8 - 14, den genauen Wert kann ich dir nicht sagen, über die Api und deinem Adapter komme ich auf den Wert 17

Wie wird das berechnet? Könnte man das vielleicht abgleichen?

Ansonsten, danke für deine Zeit, ich weiß das ist viel Arbeit.

**Comment by smarthausleben** [comment]
Grundsätzlich ist die Bestimmung der tatsächlichen Wasserhärte eine Wissenschaft für sich und eigentlich nur mit sehr viel mehr Messaufwand möglich.
Allerdings gibt die Leitfähigkeit schon einen ziemlich guten Anhaltspunkt. Auch dazu ist das Internet voll von unterschiedlichen Herangehensweisen und Berechnungen.

Mein Adapter berechnet die deutsche Wasserhärte anhand eines Faktors welchen du in den Einstellungen auch selbst anpassen kannst. Den Faktor habe ich im Internet recherchiert und ich habe Diesen genommen welcher am häufigsten herangezogen wird. Unter Issue #6 hat mich dann noch ein Anwender darauf hingewiesen, dass der Leitfähigkeitswert und damit letztendlich auch die Härte auch noch von der Wassertemperatur abhängig ist und man diesen rechnerisch kompensieren könnte. Das habe ich dann implementiert, so dass der Härtegrad dann aus der temperaturkompensierten Leitfähigkeit [CNDEC25] berechnet wird, wenn im System ein Temperaturfühler verbaut ist. Die Details dazu findest du, wie schon geschrieben, unter Issue #6 

![image](https://user-images.githubusercontent.com/101345409/184629237-b8e53976-6bb2-45a2-892f-771315997aa6.png)

**Comment by weindler** [comment]
Hi, ist mir schon klar, mir geht es nur daß die 2 Sachen zusammenstimmen siehe Bilder.
![status syr cloud connect](https://user-images.githubusercontent.com/41335851/184631765-831f9c64-538c-411b-9e99-c53939511125.jpg)
![Syr Wasserhärte Wamo](https://user-images.githubusercontent.com/41335851/184631784-01198776-c08f-42ab-9f8a-035c08f84d77.jpg)

In der Cloud bin ich unter 14, und im Broker bin ich über 16

**Comment by smarthausleben** [comment]
Wie ich ja schon geschrieben habe, darüber gibt es sehr viele Tabellen im Internet und bei den meisten dieser Tabellen ist der Leitwert noch nicht einmal Linear zum Leitwert 🙄​

Wenn du z.B. mal die Tabellen (Bilder unten) als Beispiel nimmst, dann wäre bei dieser der Durchschnittsfaktor **`0,0296041666666667`**, also niedriger wie der aktuelle Default Wert des Adapters. Trage doch diesen mal in deinen Einstellungen ein und berichte kurz ob dieser Faktor der "Realität" näher kommt..

Ich habe leider nur den Polygonvatro und auf dessen APP sehe ich, trotz Sensoren, leider keinen Härtegrad und kann daher nicht testen. Wenn der obige Wert besser passt, könnte ich diesen als neuen Default Wert im Adapter hinterlegen.

[Quelle zu dieser Tabelle](http://www.pewa.de/DATENBLATT/DBL_HA_BERICHT-LEITFAEHIGKEIT_DBL_DEUTSCH.pdf)
![image](https://user-images.githubusercontent.com/101345409/184635459-33fbd39f-1744-419f-a2c0-dda921917011.png)

**Meine Berechnung eines Durchschnittsfaktors:**
![image](https://user-images.githubusercontent.com/101345409/184636541-bec6b0eb-0dc9-44e9-9afc-6162f2ee9438.png)

**Comment by smarthausleben** [comment]
Hast du es mit dem neuen Faktor getestet? Kann ich den Punkt schließen?

**Comment by weindler** [comment]
ja es ist besser geworden, schließe hiermit das Issue.

**Comment by smarthausleben** [comment]
Danke für deine Rückmeldung 👍​ Dann werde ich diesen Faktor mal als Default Wert für den Adapter nehmen.
