### ISSUE TITLE
Warning if volume leakage is set to value > 1900

### ISSUE THREAD

**Issue by pustelbaer** [smarthausleben/ioBroker.wamo#24]
The SYR App allows to configure volume leakage values up to 9000 liters.
In this case Wamo repeatedly shows a warning message:

<html><body>

  | warn | State value to set for "wamo.0.Device.Profiles.4.PV4" has value "9000" greater than max "1900"
-- | -- | --

</body>
</html>

**Comment by smarthausleben** [comment]
Fixed in version v0.4.0
