### ISSUE TITLE
Sync generate many errors over the day

### ISSUE THREAD

**Issue by jupzup** [smarthausleben/ioBroker.wamo#28]
I get many errors over the day. It is possible to disable this Log states ? Maybe the polling interval is to short or what is the reason for this ?

`

0 | 2023-06-28 07:14:24.194 | error | AxiosError: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:18.194 | error | async getData(SRO, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:18.194 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:18.153 | error | async getData(71, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:18.153 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:12.109 | error | getDeviceProfilesData -> Error from UpdateProfileState -> Profile Number:6 stateID:Device.Profiles.6.PB6 ParameterID:PB6
wamo.0 | 2023-06-28 07:14:12.109 | error | Cannot read properties of null (reading 'getPB6')
wamo.0 | 2023-06-28 07:14:12.109 | error | getDeviceProfilesData -> Error from get_DevieProfileParameter Profile Number:6 ParameterID:PB6
wamo.0 | 2023-06-28 07:14:12.109 | error | async get_DevieProfileParameter(ProfileNumber, ParameterID, IPadress, Port): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:06.026 | error | async getData(SRO, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:06.026 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:05.984 | error | async getData(71, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:14:05.984 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:59.983 | error | get_DevieParameter -> set_FACTORY_Mode() ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:59.952 | error | getDeviceProfilesData -> Error from UpdateProfileState -> Profile Number:6 stateID:Device.Profiles.6.PF6 ParameterID:PF6
wamo.0 | 2023-06-28 07:13:59.952 | error | Cannot read properties of null (reading 'getPF6')
wamo.0 | 2023-06-28 07:13:59.952 | error | getDeviceProfilesData -> Error from get_DevieProfileParameter Profile Number:6 ParameterID:PF6
wamo.0 | 2023-06-28 07:13:59.952 | error | async get_DevieProfileParameter(ProfileNumber, ParameterID, IPadress, Port): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:48.009 | error | get_DevieParameter -> set_FACTORY_Mode() ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:47.900 | error | AxiosError: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:47.875 | error | AxiosError: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:35.901 | error | AxiosError: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:35.874 | error | AxiosError: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:29.900 | error | async getData(SRO, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:29.900 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:29.872 | error | async getData(71, 192.168.2.147:5333 ERROR: Error: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:29.872 | error | async get_DevieParameter(Parameter): Request got no response: timeout of 6000ms exceeded
wamo.0 | 2023-06-28 07:13:23.829 | error | async get_DevieParameter(Parameter) -> await this.clear_SERVICE_FACTORY_Mode() - ERROR: Error: timeout of 6000ms exceeded
email.0 | 2023-06-28 07:06:23.058 | info

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">`

**Comment by smarthausleben** [comment]
Hello jupzup,

the messages you are getting occur if data requests to the unit will not be answer from the device and therefore an indication of a communication problem with the device itself. Usually the root cause for this is a bad WiFi connection. Did you change anything in this area? Polling time is not the problem because then you would get messages like “INTERFACE BUSSY” if for example a LONG request was trigger but another request was running . All data requests to the unit will be send sequential. This means that the adapter is sending a new request only if the last one was answered correctly or something went wrong (Timeouts, No Response, etc.). So, the logging data you have provided clearly indicate that some of the requests where answered but others not.

Other heavy communication, maybe with the SYR cloud, could also be a reason for timed out requests to the device API. But this should occur, if at all, only temporarily.

So WiFi connection is probably the cause for this messages.

**Comment by smarthausleben** [comment]
More options to select which logging messages will be generated are implemented into version v0.4.0
