### ISSUE TITLE
Has to Be Type Sring but Received Number

### ISSUE THREAD

**Issue by weindler** [smarthausleben/ioBroker.wamo#33]
Hi, danke wollte mal deinen Adapter in der INstanzeinstellung auf "Info" stellen, dann kommen viele solche Warnungen.

`<html><body>

wamo.0 | 2023-12-16 12:36:08.744 | info | State value to set for "wamo.0.Device.Settings.BUZ" has to be type "string" but received type "number"
-- | -- | -- | --
wamo.0 | 2023-12-16 12:36:08.712 | info | State value to set for "wamo.0.Device.Settings.DRP" has to be type "string" but received type "number"
wamo.0 | 2023-12-16 12:36:08.676 | info | State value to set for "wamo.0.Device.Settings.DMA" has to be type "string" but received type "number"

</body>
</html>`

Vielleicht kannst du da mal schauen, ansonsten danke dir und schöne Weihnachten.

**Comment by smarthausleben** [comment]
Some states have changed their type in summer of 2022. Existing states will not be touched during an update. 

Unfortunately even translations and remarks will not be updated if they have changed. The only solution is to delete the affected states and restart the adapter.

Type changes happened in this two releases.

```
0.2.10 (2022-09-19)
•	(smarthausleben) state types changed UNI, PSD, CSD, TSD, T2`
0.2.9 (2022-08-12)
•	(smarthausleben) state types changed ATP, BSA, BUZ, DMA, DRP, DWL, IDS, LNG, LWT
```

All state changes are documented in the README and the older ones in the CHANGELOG_OLD File https://github.com/smarthausleben/ioBroker.wamo/blob/main/CHANGELOG_OLD.md 
Important Information about major and braking changes are also found in README and more detailed in the WIKI https://github.com/smarthausleben/ioBroker.wamo/wiki
