### ISSUE TITLE
Warning message device busy

### ISSUE THREAD

**Issue by woessmich** [smarthausleben/ioBroker.wamo#4]
The log regularly shows the warning message
[async getData(statesToGet)] Device interface is bussy!
Seems like the adapter does not wait until the device is responding before sending out another request?

**Comment by ACDelta** [comment]
Same problem here, 
After starting adapter, i immediatly get a warn "[onUnload(callback)] was hit" About 5 Minutes later, i have "[async getData(statesToGet)] Device interface is busy" in the log

**Comment by smarthausleben** [comment]
Related to #1

**Comment by smarthausleben** [comment]
fixed in release v0.1.5
