### ISSUE TITLE
[Enhancement] conductivity at 25°C

### ISSUE THREAD

**Issue by woessmich** [smarthausleben/ioBroker.wamo#6]
In order to make conductivity values comparable and independent from water temperature (conductivity heavily changes with temperature) and probably also to get better results for water hardness (using the corrected conductivity) an additional value could be calculated by the adapter based on formula (A4) on from this page:
[](https://www.aqion.de/site/50)

**Comment by smarthausleben** [comment]
I can't check your proposed formula because link to page is missing. Please provide the formula here.

**Comment by smarthausleben** [comment]
Will be implemented in next release.

![image](https://user-images.githubusercontent.com/101345409/180427253-37c219e1-3e36-47d0-9eb2-5760a655ac6d.png)
