### ISSUE TITLE
Make channel "Absperrung" and "Profil" writable

### ISSUE THREAD

**Issue by swenp76** [smarthausleben/ioBroker.wamo#8]
Some values can be sent and set to the device, e.g. to open/close the valve or to set the current profile.

The Safe-Tec syntax is:  
`http://ip-address:5333/safe-tec/set/ab/1` for open and
`http://ip-address:5333/safe-tec/set/ab/2` for close the valve.

The active profile can be set using 
`http://ip-address:5333/safe-tec/set/prf/1` for profile 1 etc.

Right now the objects are Read-Only, maybe you can implement writing to them, too.

I'm already using this function to automatically set a day/night profile and to open/close the main valve by blockly and sending http-requests, but it would be nice to have it implemented directly into the adapter.

**Comment by smarthausleben** [comment]
added in release v0.1.5
